project:
  type: website
  output-dir: docs

website:
  title: "Linux as Daily Driver"
  sidebar:
    style: "docked"
    search: true
    contents:
        - installation.qmd
        - software.qmd
        - r.qmd

format:
  html:
    theme: cosmo
    highlight-style: atom-one
    css: styles.css
    toc: true



